baseURL = ""
languageCode = "pl-pl"
title = "Koło Naukowe Informatyków | WIiNoM"
theme = "timer-hugo"

# Site Params

[params]
    #home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Koło Naukowe Informatyków"
        description = "Dołącz do nas już dziś!"
        [[params.banner.flipText]]
            title   = "TWORZYMY OPROGRAMOWANIE"
        [[params.banner.flipText]]
            title   = "PROJEKTUJEMY GRY"
        [[params.banner.flipText]]
            title   = "PROWADZIMY WARSZTATY"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "O nas"
        #content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam enim id magna mattis porttitor. Etiam dignissim tristique erat non bibendum. Donec pellentesque diam quis mauris fermentum iaculis. Maecenas et faucibus nulla. Proin vehicula ligula id gravida tempor. Aliquam eget urna tincidunt neque posuere condimentum vel et enim. Nam purus sapien, posuere nec vestibulum bibendum, pellentesque at leo."
        content = "Koło Naukowe Informatyków: spotykamy się, aby dzilić pasje i wymieniać się doświadczeniem. Staramy się sprostać Waszym oczekiwaniom oraz pomóc Wam w przygotowaniu do dalszej kariery. W ramach koła organizowane będą cykle szkolen prowadzone zarówno przez studentów jak i osoby zewnętrzne. Jesteśmy otwartym kołem, jeżeli jesteś zainteresowany dołączeniem do naszego grona, serdecznie zapraszamy!"
        image   = "images/about/about.jpg"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Ostatnie projekty"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."
