baseURL = ""
languageCode = "pl-pl"
title = "Koło Naukowe Informatyków | WIiNoM"
theme = "timer-hugo"

# Site Params
[params]
    #home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Koło Naukowe Informatyków"
        description = "Dołącz do nas już dziś!"
        [[params.banner.flipText]]
            title   = "TWORZYMY OPROGRAMOWANIE"
        [[params.banner.flipText]]
            title   = "PROJEKTUJEMY GRY"
        [[params.banner.flipText]]
            title   = "PROWADZIMY WARSZTATY"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "O nas"
        content = "Koło Naukowe Informatyków: spotykamy się, aby dzielić pasje i wymieniać się doświadczeniem. Staramy się sprostać Waszym oczekiwaniom oraz pomóc Wam w przygotowaniu do dalszej kariery. W ramach koła organizowane będą cykle szkoleń prowadzone zarówno przez studentów, jak i osoby zewnętrzne. Jesteśmy otwartym kołem, jeżeli jesteś zainteresowany dołączeniem do naszego grona, serdecznie zapraszamy!"        
        image   = "images/about/about.jpg"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Ostatnie projekty"
        subtitle= "Oto kilka naszych najnowszych prac. Na bieżąco staramy się aktualizować listę naszych projektów."

    # Contact Section about Facebook Group 
    [params.cta]
        enable  = true
        title   = "DOŁĄCZ DO NAS JUŻ DZIŚ !"
        content = "Jeśli chciałbyś do nas dołączyć, w opisie grupy Facebookowej znajdziesz wszystkie potrzebne informacje. Rekrutację prowadzimy cały rok!"
        btnText = "Grupa Koła Naukowego Informatyków"
        btnURL  = "https://www.facebook.com/groups/KoloNaukoweInformatykow/"